name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Используйте Node.js версии 16 или выше

      - name: Install stylelint and dependencies
        run: |
          npm install -g stylelint stylelint-config-standard

      - name: Lint CSS
        run: stylelint "/*.css"

      - name: Lint HTML
        run: npx htmlhint "/*.html"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
